# -*- coding: utf-8 -*-
"""Trabajo 1 POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfMRxlozKbOGjRP4M_K1FIUwgocevnHC
"""

class CalcularEdades:

    def __init__(self, edjuan):
        self.edjuan = edjuan
        self.edalber = 0
        self.edana = 0
        self.edmama = 0

    def calcular_edades(self):
        self.edalber = 2 * self.edjuan / 3
        self.edana = 4 * self.edjuan / 3
        self.edmama = self.edjuan + self.edalber + self.edana

    def mostrar_edades(self):
        print("Las edades son:")
        print("Alverto:", self.edalber)
        print("Juan:", self.edjuan)
        print("Ana:", self.edana)
        print("Mamá:", self.edmama)


edjuan = int(input("Ingrese la edad de Juan: "))

familia = CalcularEdades(edjuan)

familia.calcular_edades()
familia.mostrar_edades()

class Ejercicio5:

    def __init__(self):
        self.suma = 0
        self.x = 20
        self.y = 40

    def calcular(self):
        self.suma = self.suma + self.x
        self.x = self.x + self.y ** 2
        self.suma = self.suma + self.x / self.y

    def mostrar(self):
        print("EL VALOR DE LA SUMA ES:", self.suma)


ejercicio = Ejercicio5()
ejercicio.calcular()
ejercicio.mostrar()

class Empleado:

    def __init__(self):
        self.horas = 48
        self.valor_hora = 5000
        self.porcentaje_retencion = 12.5
        self.salario_bruto = 0
        self.retencion = 0
        self.salario_neto = 0

    def calcular(self):
        self.salario_bruto = self.horas * self.valor_hora
        self.retencion = self.salario_bruto * self.porcentaje_retencion / 100
        self.salario_neto = self.salario_bruto - self.retencion

    def mostrar(self):
        print("SALARIO BRUTO:", self.salario_bruto)
        print("RETENCION:", self.retencion)
        print("SALARIO NETO:", self.salario_neto)


empleado = Empleado()
empleado.calcular()
empleado.mostrar()

class Numero:

    def __init__(self, numero):
        self.numero = numero
        self.cuadrado = 0
        self.cubo = 0

    def calcular(self):
        self.cuadrado = self.numero ** 2
        self.cubo = self.numero ** 3

    def mostrar(self):
        print("CUADRADO:", self.cuadrado)
        print("CUBO:", self.cubo)


numero = float(input("Ingrese un número: "))

n = Numero(numero)

n.calcular()
n.mostrar()

import math

class Circulo:

    def __init__(self, radio):
        self.radio = radio
        self.area = 0
        self.longitud = 0

    def calcular(self):
        self.area = math.pi * self.radio ** 2
        self.longitud = 2 * math.pi * self.radio

    def mostrar(self):
        print("AREA:", self.area)
        print("LONGITUD DE LA CIRCUNFERENCIA:", self.longitud)


radio = float(input("Ingrese el radio del círculo: "))

circulo = Circulo(radio)

circulo.calcular()
circulo.mostrar()